// Structure materials. The client turns these into procedural textures; the
// simulation uses them for footstep surfaces and bullet impact effects.

export const MAT = {
  CONCRETE: 0,
  BRICK: 1,
  METAL: 2,
  WOOD: 3,
  SANDBAG: 4,
  ROOF_TILE: 5,
  ROOF_METAL: 6,
  ASPHALT: 7,
  DARK_METAL: 8,
  PLASTER: 9,
  WINDOW: 10,
  CRATE: 11,
  CONTAINER_RED: 12,
  CONTAINER_BLUE: 13,
  CONTAINER_GREEN: 14,
  ROCK: 15,
  CANVAS: 16,
  CAMO_NET: 17,
  PAINT_WHITE: 18,
  HAZARD: 19,
  RUST: 20,
  WOOD_DARK: 21,
  CONCRETE_DARK: 22,
  GRAVEL: 23,
  LAMP: 24,
  FLAG_BLUE: 25,
  FLAG_RED: 26,
  TARGET: 27,
  HESCO: 28,
  PLASTER_WARM: 29,
  STONE: 30,
  RED_CROSS: 31,
  CONTAINER_TAN: 32,
  FOLIAGE: 33,
  TRUNK: 34,
  PINE: 35,
  SNOW_ROOF: 36,
  ICE: 37,
  BLACK: 38,
  OLIVE: 39,
};

export const MAT_COUNT = 40;

// Base colours (linear-ish sRGB 0..1) and texture pattern hints for the client.
export const MAT_INFO = [
  { name: 'concrete', color: [0.62, 0.61, 0.58], pattern: 'concrete', surface: 'concrete' },
  { name: 'brick', color: [0.55, 0.3, 0.22], pattern: 'brick', surface: 'concrete' },
  { name: 'metal', color: [0.5, 0.53, 0.55], pattern: 'corrugated', surface: 'metal' },
  { name: 'wood', color: [0.55, 0.41, 0.26], pattern: 'planks', surface: 'wood' },
  { name: 'sandbag', color: [0.6, 0.53, 0.38], pattern: 'sandbag', surface: 'dirt' },
  { name: 'roof_tile', color: [0.52, 0.25, 0.18], pattern: 'tiles', surface: 'concrete' },
  { name: 'roof_metal', color: [0.38, 0.42, 0.4], pattern: 'corrugated', surface: 'metal' },
  { name: 'asphalt', color: [0.2, 0.2, 0.21], pattern: 'asphalt', surface: 'concrete' },
  { name: 'dark_metal', color: [0.24, 0.26, 0.27], pattern: 'panel', surface: 'metal' },
  { name: 'plaster', color: [0.78, 0.76, 0.7], pattern: 'windows', surface: 'concrete' },
  { name: 'window', color: [0.16, 0.2, 0.23], pattern: 'glass', surface: 'metal' },
  { name: 'crate', color: [0.56, 0.44, 0.28], pattern: 'crate', surface: 'wood' },
  { name: 'container_red', color: [0.55, 0.2, 0.16], pattern: 'container', surface: 'metal' },
  { name: 'container_blue', color: [0.18, 0.3, 0.5], pattern: 'container', surface: 'metal' },
  { name: 'container_green', color: [0.24, 0.4, 0.26], pattern: 'container', surface: 'metal' },
  { name: 'rock', color: [0.45, 0.44, 0.41], pattern: 'rock', surface: 'concrete' },
  { name: 'canvas', color: [0.42, 0.44, 0.3], pattern: 'canvas', surface: 'dirt' },
  { name: 'camo_net', color: [0.3, 0.35, 0.22], pattern: 'net', surface: 'dirt' },
  { name: 'paint_white', color: [0.88, 0.88, 0.85], pattern: 'flat', surface: 'concrete' },
  { name: 'hazard', color: [0.85, 0.7, 0.15], pattern: 'hazard', surface: 'metal' },
  { name: 'rust', color: [0.45, 0.28, 0.18], pattern: 'rust', surface: 'metal' },
  { name: 'wood_dark', color: [0.33, 0.24, 0.16], pattern: 'planks', surface: 'wood' },
  { name: 'concrete_dark', color: [0.4, 0.4, 0.39], pattern: 'concrete', surface: 'concrete' },
  { name: 'gravel', color: [0.5, 0.48, 0.44], pattern: 'gravel', surface: 'dirt' },
  { name: 'lamp', color: [1.0, 0.92, 0.7], pattern: 'flat', surface: 'metal', emissive: true },
  { name: 'flag_blue', color: [0.2, 0.36, 0.66], pattern: 'flat', surface: 'dirt' },
  { name: 'flag_red', color: [0.66, 0.18, 0.16], pattern: 'flat', surface: 'dirt' },
  { name: 'target', color: [0.9, 0.88, 0.82], pattern: 'target', surface: 'wood' },
  { name: 'hesco', color: [0.56, 0.52, 0.4], pattern: 'hesco', surface: 'dirt' },
  { name: 'plaster_warm', color: [0.8, 0.7, 0.55], pattern: 'windows', surface: 'concrete' },
  { name: 'stone', color: [0.6, 0.57, 0.5], pattern: 'stone', surface: 'concrete' },
  { name: 'red_cross', color: [0.9, 0.9, 0.9], pattern: 'redcross', surface: 'dirt' },
  { name: 'container_tan', color: [0.6, 0.52, 0.36], pattern: 'container', surface: 'metal' },
  { name: 'foliage', color: [0.2, 0.33, 0.15], pattern: 'leaves', surface: 'dirt' },
  { name: 'trunk', color: [0.3, 0.22, 0.15], pattern: 'bark', surface: 'wood' },
  { name: 'pine', color: [0.13, 0.25, 0.16], pattern: 'leaves', surface: 'dirt' },
  { name: 'snow_roof', color: [0.9, 0.92, 0.95], pattern: 'flat', surface: 'dirt' },
  { name: 'ice', color: [0.7, 0.8, 0.86], pattern: 'flat', surface: 'concrete' },
  { name: 'black', color: [0.08, 0.08, 0.09], pattern: 'flat', surface: 'metal' },
  { name: 'olive', color: [0.3, 0.33, 0.22], pattern: 'panel', surface: 'metal' },
];

// Materials that bullets can shoot through (thin, soft). Everything else blocks.
export const PENETRABLE = new Set([MAT.CANVAS, MAT.CAMO_NET, MAT.WINDOW, MAT.FOLIAGE, MAT.PINE, MAT.FLAG_BLUE, MAT.FLAG_RED]);
